## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the synthetic population in the output_path
  - matsim.simulation.prepare # To generate config files for the simulation
  - matsim.runtime.eqasim # To update the jar according to modifications in RunSimulation.java
  - matsim.output # To prepare the simulation (2 iterations) - must be re-run if modifications in RunSimulation.java were made
  - matsim.simulation.full_run # To run the full MATSim simulation

#  - analysis.synthesis.population # Generates tables to compare synthetic population to source data
#  - analysis.grid.comparison_flow_volume # Generates grids showing the volumes of the synthetic population (by age group and trip purpose) / 
  # or comparing two synthetic populations if comparison_file_prefix is specified in the config section (below)

# Here the configuration of the pipeline starts
config:
  # Some general configuration
  processes: 6

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: emp

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.02 # default=0.001
  random_seed: 1234

  # Zone to study
  regions: [11] # (11=IDF)
  # departments: [78] # default=[]

  # Paths to the input data and where the output should be stored
  data_path: data_sources
  output_path: output

  # GTFS path (default=gtfs_idf)
  gtfs_path: gtfs_idf

  # Only interesting if you run the simulation
  java_memory: 14G

  # Activate if you want to run mode choice
  mode_choice: false

  # Uncomment to use the bhepop2 package for attributing income
  # income_assignation_method: bhepop2

  # To export detailed link geometries
  export_detailed_network: True # Exports the detailed geometries of every network link

  # Analysis pipeline
  output_prefix: simulated_ # prefix of output files (synthetic population)
  # comparison_file_prefix: compared_ # prefix of files to be compared with the simulated population (have to be in the output folder)
  analysis_from_file: true # false = last synthetic population is studied (loaded from cache) / true = last outputed files are studied (loaded from output folder)

  # When running the full MATSim simulation, activate to rerun the simulation even if output already exists
  force_full_rerun: true

  # eqasim_path: matsim-java